name: deploy

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout source
      - name: Checkout
        uses: actions/checkout@v3
      # generate artifacts
      - name: install and build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build:docs
      - name: github-ci
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
